STICMedicaps/Hacktoberfest

c/Doubly_Linked_List.c

Hey there,
Added a C program that performs various operations on Doubly Linked Lists.

Added a program with various operations on Doubly Linked List

---

java/balancedParentheses.java

Added balancedParentheses.java

Added balancedParentheses.java

---

c/AmicableNumbers.c
c/PerfectNumber.c

Program to check whether the given number is a Perfect number or not.

Added PerfectNumber.c

---

python/resize.py

A simple script to resize images with python (p.s this is for hacktoberfest)

Bulk Image resizer

---

java/PalindromeNumber.java

Added palindrome number in java

Palindrome Number

---

cpp/dist_btw_2nodes.cpp

Here, I found the distance between 2 nodes in a Binary Search Tree using the C++ programming language.

Distance between 2 nodes

---

c/alphabetnumberorcharacter.c

Program to check whether the entered character is an alphabet, a number or a special character using ASCII values.

Alphabet, Number or Special Character

---

cpp/Fibbionaci.c++
cpp/O-1 Knapsack.c++
cpp/egg_dropping.c++
cpp/min_no_of_coin.c++
cpp/painting_fence.c++
cpp/subset_sum.c++
cpp/unbounded_knapsack.c++

Dynamic programing  problem

---

java/InsertionSort.java

I had added insertion sort program in java folder.

InsertionSort in Java

---

c/Floyd's Algo.c
c/Krushkals.c
c/Topological Sort.c
c/Warshall's.c

Added Warshall's Algorithm

---

c/Floyd's Algo.c

Added a program that contains Floyd's Algorithm in C

Added Floyd's

---

c/Floyd's Algo.c
c/Krushkals.c
c/Topological Sort.c

Implemented topological sorting using c

Added Topological sort

---

c/Covid_Tracker.c

Covid Tracker Program In C.
This program basically checks if one is infected or not on the basis of his symptoms.

Covid Tracker Program In C

---

cpp/selectionSort_mRahulRoy.cpp

Selection Sort Implimentation In C++. waiting for the commit to be mereged.

Selection Sort Implimentation In C++

---

python/air_quality_detector.py

This is mini project in python which gives us the air quality of city which we give as input which fetches the result directly from site.

Air Quality Detector Python Project

---

cpp/Morre's Voting Algorithm_mRahulRoy.cpp

Morre's Voting Algorithm For Majority Elements in an array/vector.

Morre's Voting Algorithm For Majority Elements

---

java/armstrong.java

i have added code to find the armstrong number in java

Added code to find armstrong number

---

cpp/LargestClique.cpp

CPP program to find largest clique 

---

python/password_manager.py

added password manager program in python folder.

Password Manager [Python]

---

c/MergeSort.c

Added Merge Sort
